### ISSUE TITLE
Docker in new app

### ISSUE THREAD

**Issue by jhsu802701** [rubyonracetracks/docusaurus_neutrino#1]
* Dockerfile:
```
FROM node:lts
USER node
```
* docker-compose.yml:
```
version: "3"

services:
  docusaurus:
    build: .
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - .:/home/node/neutrino
    working_dir: /home/node/neutrino/website
    user: node
    command:
      - yarn
      - start
```
* bin/yinstall:
```
#!/bin/bash
set -e

docker-compose run --rm docusaurus yarn install
```
